name: docker bats tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          mv tests/.env.docker.default tests/.env.docker
          mv tests/.secrets.default tests/.secrets
          docker build --build-arg="GO_LIBRARY=go1.23.1.linux-amd64.tar.gz" \
            --build-arg="AWS_CLI=awscli-exe-linux-x86_64.zip" --build-arg="MC_FOLDER=linux-amd64" \
            --progress=plain -f tests/Dockerfile_test_bats -t bats_test .

      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Run Docker Container
        run: docker-compose -f tests/docker-compose-bats.yml up --exit-code-from s3api_np_only s3api_np_only
